### ISSUE TITLE
homepage from pubspec goes to unknown domain

### ISSUE THREAD

**Issue by sethladd** [daftspaniel/simplegamelib#1]
It goes to https://www.divingintodart.com/ which doesn't resolve for me :(

Check it out here: https://pub.dartlang.org/packages/simplegamelib

**Comment by daftspaniel** [comment]
Thanks @sethladd  - should really be http. A proper homepage will appear when introduction blog post is posted.

**Comment by daftspaniel** [comment]
Fixed URL to be http and republished.
